language: go
go:
- 1.9.x
branches:
  only:
  - master
sudo: required
services:
- docker
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- make release coverage
- echo "Pushed image ${DOCKER_IMAGE}:${TRAVIS_COMMIT}"
after_script:
- ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - DOCKER_IMAGE=fiunchinho/iam-role-annotator
  - DOCKER_USER=fiunchinho
  # DOCKER_PASS
  - secure: "MtgwQZ1JVYuZp+8v1lBXP6dAkVAslgzvAmEfOwcwEcccjaKrbFT/3apT4CE+FvagwzZOw0OdevxRWa/XHk7hSLjteAUjsbRxiJZIJ+oIiR7cAZiMcUrPuorYBH/umyV5JzEv6owWtQWyIv4lDJ7NpOSJ/YRgbdup38laGHQbIWczNPgIideJiRr7T2udtwFPF1j0Go0xL9ypsTSyOf6yqtjli6IJJwbLeV1hGIrJi9MTYqGzsgqyTaESxU1Wz2KC9vRM3SYcVevvkZH+R9epq0uuytdH6JpJ8dwDVyQAhHTG8gEQwK6bkuSzgpVWhaaMIW5sWsbNZal6KdfqRJ6cDG2cB2ha8t4+iIly/Yxaet0DWqBpLI1KKd2dI2wfo673ud9CJx4CjDu5yt7TF+kxhxd0+NTno+FCKxeBsVPX9qHALaXn0ITbB+czj5/dXChKRAnct0nW4uNQg9fgCGamRiYM99kmglDX04TpZL5P1RexLmYUol0oRwXysDjXJWbFHDIR7WHR8pGSFr8wFE3RA3zwYrlKPXfkcLmNOZw5e51d+Tmjp4vUyEIydFpfDK/k2nnlXzUrgEgFpsXNnrsjUubRHAnfJs2Rp9ZfobMTjmd1aeI0N0E90LcUlhyJt2SCoxT9MDR0G0bHFM73FiI3OKiUPu1tSAj6shLqHi867Fo="
  - CC_TEST_REPORTER_ID=e3b52b7a82834f79e2ff72e3ed3476bb975c416e12d9f3c30bd3cfabac82a22a
