#!/usr/bin/env bash

set -e

# Create cover profile
COVER_MODE="count"
echo "mode: $COVER_MODE" > profile.cov
for package in $(go list ./... | grep -v vendor); do
   go test -v -cover -covermode=${COVER_MODE} -coverprofile=profile.cov.tmp ${package}
   [[ -f "profile.cov.tmp" ]] && (cat profile.cov.tmp | tail -n +2 >> profile.cov)
   rm -f profile.cov.tmp
done

# Print code coverage details
go tool cover -func profile.cov

# Generate coverage report
gocov convert profile.cov | gocov-xml > coverage.xml
