#!/usr/bin/env bash

set -e

# Create cover profile
for pkg in $(go list ./... | grep -v vendor); do
   go test -v -cover -coverprofile=$(echo $pkg | tr / -).cover $pkg
done

echo "mode: set" > c.out
grep -h -v "^mode:" ./*.cover >> c.out
rm -f *.cover

# Print code coverage details
go tool cover -func c.out

# Generate coverage report
gocov convert c.out | gocov-xml > coverage.xml
